### ISSUE TITLE
[Tajweed: Kemenag] surah 2

### ISSUE THREAD

**Issue by axmad386** [kodepandai/colorful-quran#6]
Need to complete tajweed anotation kemenag version for surah 2
PR are welcome, please separate PR for each aya

## List of aya
- [x] #7
- [x] #8 assigned to @axmad386 
- [x] #9 assigned to @yudianwebdev 
- [x] #14 assigned to @hilmiardani
- [x] #21

please fill in comment if you wanna contribute

**Comment by hilmiardani** [comment]
Verse 21-40

**Comment by axmad386** [comment]
OK, just create new PR :ok_hand:

**Comment by axmad386** [comment]
Hello everyone
please see #4. I will make the parent of this task to pending
